name: '"AWS CodeBuild run build" Action For GitHub Actions'
description: 'Execute CodeBuild::startBuild for the current repo.'
branding:
  icon: 'cloud'
  color: 'orange'
inputs:
  project-name:
    description: 'AWS CodeBuild Project Name'
    required: true
  endpoint:
    description: 'API endpoint'
    required: false
  use-credentials:
    description: 'Comma separated list of environment variables to send to CodeBuild'
    required: false
    default: 'true'
  buildspec-override:
    description: 'Location of the buildspec file'
    default: 'ci/build.spec.yaml'
    required: true
outputs:
  aws-build-id:
    description: 'The AWS CodeBuild Build ID for this build.'
runs:
  using: 'node12'
  main: 'dist/index.js'